### ISSUE TITLE
validate seed file before it's added to ISO

### ISSUE THREAD

**Issue by oregonpillow** [cn246-admin/mkiso#3]
It's a little bit annoying to install your ISO then find out during installation that debian finds an error in your preseed file. Luckily there is a way to validate the file beforehand.

**Comment by chuckn246** [comment]
Agreed, thank you for finding that feature!

**Comment by oregonpillow** [comment]
I read about it here https://wiki.debian.org/DebianInstaller/Preseed#Custom_preseed_files
