### ISSUE TITLE
add debconf-set-selections to requirements?

### ISSUE THREAD

**Issue by oregonpillow** [cn246-admin/mkiso#5]
Do you think `debconf-utils` should be added within the README requirements since this package contains `debconf-set-selections` ? I know it's always included within Debian....but wasn't sure for transparency purposes if we should explicitly include it.

reference:
https://packages.debian.org/sid/debconf-utils  
https://wiki.debian.org/PackageManagement/Preseed

**Comment by chuckn246** [comment]
Honestly, I'm not sure if having `debconf-utils` is necessary.

Connecting to a Debian virtual machine, [debconf-set-selections](https://manpages.debian.org/stable/debconf/debconf-set-selections.1.en.html) is available even when [debconf-utils](https://packages.debian.org/stable/debconf-utils) is not installed:

```
$ apt policy debconf-utils
debconf-utils:
  Installed: (none)
  Candidate: 1.5.77
  Version table:
     1.5.77 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        500 http://deb.debian.org/debian bullseye/main i386 Packages

$ command -v debconf-set-selections
/usr/bin/debconf-set-selections
```

I can add it to the README just in case.

**Comment by chuckn246** [comment]
Added to the README, thanks!
